engines:
  rubocop:
    enabled: true
  csslint:
    enabled: true
  coffeelint:
    enabled: true
ratings:
   paths:
   - "app/**/*"
   - "lib/**/*"
   - "**.rb"
   - "**.go"
exclude_paths:
  - 'spec/**/*'
  - 'vendor/**/*'
