language: ruby
rvm:
 - "2.2.3"
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
services:
  - postgresql
addons:
  postgresql: "9.4"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.travis.yml config/database.yml
